liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        # Define your filter sets here
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
